### ISSUE TITLE
ApiException: 200 Status Code

### ISSUE THREAD

**Issue by ghunkins** [fingerprintjs/fingerprint-pro-server-api-python-sdk#73]
I am receiving a lot of `ApiException` errors even when a `200` response is being returned.

Below is the stack trace:

```
Traceback (most recent call last):
  File "/app/main.py", line 213, in check_fjs_allowed
    fjs_resp = request.app.fjs.get_event(fjs_token)
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/api/fingerprint_api.py", line 177, in get_event
    (data) = self.get_event_with_http_info(request_id, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/api/fingerprint_api.py", line 260, in get_event_with_http_info
    raise e
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/api/fingerprint_api.py", line 238, in get_event_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/api_client.py", line 300, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/api_client.py", line 176, in __call_api
    raise error
fingerprint_pro_server_api_sdk.rest.ApiException: (200)
```

Here is a related stack trace that is likely relevant:

```
 Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/api_client.py", line 170, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/api_client.py", line 254, in deserialize
    return ApiClientDeserializer.deserialize(data, response_type)
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/api_client.py", line 520, in deserialize
    return ApiClientDeserializer.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/api_client.py", line 602, in __deserialize_model
    kwargs[attr] = ApiClientDeserializer.deserialize(value, attr_type)
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/api_client.py", line 520, in deserialize
    return ApiClientDeserializer.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/api_client.py", line 602, in __deserialize_model
    kwargs[attr] = ApiClientDeserializer.deserialize(value, attr_type)
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/api_client.py", line 520, in deserialize
    return ApiClientDeserializer.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/api_client.py", line 602, in __deserialize_model
    kwargs[attr] = ApiClientDeserializer.deserialize(value, attr_type)
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/api_client.py", line 520, in deserialize
    return ApiClientDeserializer.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/api_client.py", line 604, in __deserialize_model
    instance = klass(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/models/velocity_result.py", line 58, in __init__
    self.distinct_ip = distinct_ip
  File "/usr/local/lib/python3.9/site-packages/fingerprint_pro_server_api_sdk/models/velocity_result.py", line 80, in distinct_ip
    raise ValueError("Invalid value for `distinct_ip`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `distinct_ip`, must not be `None` 
```

It appears that the `distinct_ip` is required by this library, but the API returns a 200 response code for payloads that do not include this value.

**Comment by ilfa** [comment]
Hi @ghunkins!

Sorry, I completely missed your issue. Do you still reproduce this problem?
